"""add merged to pr_state

Revision ID: 18e1bc15cd7b
Revises: d0ed8c1affe8
Create Date: 2026-06-02 22:43:16.241093

"""
from typing import Sequence, Union
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '18e1bc15cd7b'
down_revision: Union[str, None] = 'd0ed8c1affe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate doesn't detect Enum changes, so we must add it manually.
    op.execute("COMMIT")
    op.execute("ALTER TYPE pr_state ADD VALUE IF NOT EXISTS 'MERGED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
