"""update review model

Revision ID: 8f11cb5dd113
Revises: d527f0980ea8
Create Date: 2026-06-15 11:25:16.988691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f11cb5dd113'
down_revision: Union[str, None] = 'd527f0980ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('commit_sha', sa.String(length=40), nullable=False, server_default='unknown'))
    op.add_column('reviews', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_reviews_pr_commit_sha', 'reviews', ['pr_id', 'commit_sha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_pr_commit_sha', 'reviews', type_='unique')
    op.drop_column('reviews', 'attempt_count')
    op.drop_column('reviews', 'commit_sha')
    op.drop_column('reviews', 'last_error')
    op.drop_column('reviews', 'started_at')
    # ### end Alembic commands ###
