"""Add github_updated_at and unique constraint to pull_requests

Revision ID: d527f0980ea8
Revises: 18e1bc15cd7b
Create Date: 2026-06-13 13:24:55.523031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d527f0980ea8"
down_revision: Union[str, None] = "18e1bc15cd7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pull_requests",
        sa.Column("github_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_unique_constraint(
        "uq_pull_requests_repo_github_pr", "pull_requests", ["repo_id", "github_pr_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_pull_requests_repo_github_pr", "pull_requests", type_="unique"
    )
    op.drop_column("pull_requests", "github_updated_at")
    # ### end Alembic commands ###
